version: '3.8'

services:
  hazelcast_1:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5701"
      - "HZ_CLUSTERNAME=dev"
      - "PROMETHEUS_PORT=9999"
      - "JAVA_OPTS=-Xms512M -Xmx1024M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5701:5701
      - 9999:9999
    networks:
      - hazelcast-network

  hazelcast_2:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5702"
      - "HZ_CLUSTERNAME=dev"
      - "PROMETHEUS_PORT=8888"
      - "JAVA_OPTS=-Xms512M -Xmx1024M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5702:5702
      - 8888:8888
    networks:
      - hazelcast-network

  hazelcast_3:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5703"
      - "HZ_CLUSTERNAME=dev"
      - "PROMETHEUS_PORT=7777"
      - "JAVA_OPTS=-Xms512M -Xmx1024M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5703:5703
      - 7777:7777
    networks:
      - hazelcast-network
  
  hazelcast_mc:
    image: hazelcast/management-center:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
