version: '3.8'

services:
  hazelcast_1:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5701"
      - "HZ_CLUSTERNAME=dev"
      - "JAVA_OPTS=-Xms512M -Xmx512M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5701:5701
    networks:
      - hazelcast-network

  hazelcast_2:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5702"
      - "HZ_CLUSTERNAME=dev"
      - "JAVA_OPTS=-Xms512M -Xmx512M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5702:5702
    networks:
      - hazelcast-network

  hazelcast_3:
    image: hazelcast/hazelcast:5.3.2
    environment:
      # - "HZ_NETWORK_PUBLICADDRESS=10.100.1.111:5703"
      - "HZ_CLUSTERNAME=dev"
      - "JAVA_OPTS=-Xms512M -Xmx512M -Dhazelcast.jmx=true"

    restart: always
    ports:
      - 5703:5703
    networks:
      - hazelcast-network
  
  hazelcast_mc:
    image: hazelcast/management-center:latest
    restart: always
    environment:
    - "MC_ADMIN_USER=admin"
    - "MC_ADMIN_PASSWORD=P4ssw0rd"
    - "MIN_HEAP_SIZE='512M'"
    - "MAX_HEAP_SIZE='512M'"
    - "-Dhazelcast.mc.lock.skip=true"
    ports:
      - 8181:8080
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
